#!/usr/bin/env tsx
/**
 * Regenerates TOOLSETS.md from the live catalog (src/catalog/index.ts).
 * Run after any catalog change and commit the result - CI does not do this
 * for you.
 */
import { writeFile } from "node:fs/promises";
import { CATALOG } from "../src/catalog/index.js";
import { TOOLSET_DEFS } from "../src/catalog/toolsets.js";
import type { ToolSpec, ToolsetId } from "../src/catalog/types.js";

function renderTool(tool: ToolSpec): string {
  const status = tool.exposed === false ? `not exposed - ${tool.exposedReason}` : tool.risk;
  return `| \`${tool.name}\` | ${tool.operation.method} \`${tool.operation.path}\` | ${status} | ${tool.title} |`;
}

async function main(): Promise<void> {
  const byToolset = new Map<ToolsetId, ToolSpec[]>();
  for (const tool of CATALOG) {
    const list = byToolset.get(tool.toolset) ?? [];
    list.push(tool);
    byToolset.set(tool.toolset, list);
  }

  const exposedCount = CATALOG.filter((t) => t.exposed !== false).length;

  const lines: string[] = [
    "<!-- Generated by `npm run spec:inventory`. Do not hand-edit the tables below this line. -->",
    "",
    "# Toolsets",
    "",
    "This file is regenerated from `src/catalog/index.ts`. Run `npm run spec:inventory` after any catalog",
    "change and commit the result.",
    "",
    `${CATALOG.length} operations total, ${exposedCount} exposed as tools, ${CATALOG.length - exposedCount} intentionally not exposed (see reasons below and [ARCHITECTURE.md](ARCHITECTURE.md#whats-not-exposed-and-why)).`,
    "",
    "| Toolset | Default | Tools | Description |",
    "| --- | --- | --- | --- |",
  ];

  for (const def of TOOLSET_DEFS) {
    const count = byToolset.get(def.id)?.length ?? 0;
    if (count === 0) continue;
    lines.push(
      `| [\`${def.id}\`](#${def.id}) | ${def.defaultEnabled ? "on" : "off"} | ${count} | ${def.description} |`,
    );
  }

  for (const def of TOOLSET_DEFS) {
    const tools = byToolset.get(def.id);
    if (!tools || tools.length === 0) continue;
    lines.push(
      "",
      `## ${def.id}`,
      "",
      `${def.description} Enabled by default: **${def.defaultEnabled ? "yes" : "no"}**.`,
      "",
    );
    lines.push("| Tool | Operation | Risk | Summary |", "| --- | --- | --- | --- |");
    for (const tool of [...tools].sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(renderTool(tool));
    }
  }

  await writeFile("TOOLSETS.md", lines.join("\n") + "\n", "utf-8");
  console.error(`Wrote TOOLSETS.md (${CATALOG.length} tools across ${byToolset.size} toolsets)`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
